### PR TITLE
Add BufferLines and SetBufferLines, Deprecated some API

### PR DESCRIPTION
**Pull request by zchee**
Ref: https://github.com/neovim/neovim/pull/4083

Add
```go
BufferLines(buffer Buffer, start int, end int, strictIndexing bool) ([][]byte, error)
SetBufferLines(buffer Buffer, start int, end int, strictIndexing bool, replacement [][]byte) error
```

Deprecated
```go
BufferLine(buffer Buffer, index int) ([]byte, error)
SetBufferLine(buffer Buffer, index int, line []byte) error
DeleteBufferLine(buffer Buffer, index int) error
BufferLineSlice(buffer Buffer, start int, end int, includeStart bool, includeEnd bool) ([][]byte, error)
SetBufferLineSlice(buffer Buffer, start int, end int, includeStart bool, includeEnd bool, replacement [][]byte) error
InsertBuffer(buffer Buffer, lnum int, lines [][]byte) error
```

===

Hi.
Thanks for Neovim Go interface!
It's very fast, simple and easy to use. amazing!
And did you using deoplete-go? (I found you in stargazers) also thanks.

BTW, Neovim buffer API has been changed.
Add `buffer_get_lines`, `buffer_set_lines`, deprecated some API.
I have updated it. and add API description from [buffer.c](https://github.com/neovim/neovim/blob/master/src/nvim/api/buffer.c)
but, I'm Golang newbie.
If exists the wrong point or need to fix the `Doc` comments, Please point out.
I will revise it.

Also, Neovim have new `buffer_add_highlight` & `buffer_clear_highlight` API.
I'm split the pull request. will create.

===
Off topic:
I have a question for you.
If you don't mind, Can I send e-mail?

Thanks.

### CODE REVIEW

**Comment by garyburd** [comment]
I have the buffer line and the highlight changes ready to go on my workstation. 

 Because I am [the only known user of the package](https://godoc.org/github.com/garyburd/neovim-go/vim?importers), I am deleting the deprecated methods.

You can contact me using the email on my Github profile.

**Comment by zchee** [comment]
@

**Comment by garyburd** [comment]
I'll delete the deprecated methods after I update my other packages.  

> And did you using deoplete-go? (I found you in stargazers) also thanks.

I do not use deoplete-go or any other completion tool. I'll install deoplete-go and try it.

**Comment by zchee** [comment]
@garyburd 
> I'll delete the deprecated methods after I update my other packages.

I confirmed it https://github.com/garyburd/neovim-go/commit/8a48c3320d1e5343ec24fc1aa6cd7c2f56bd2edd. Thanks!

> I do not use deoplete-go or any other completion tool. I'll install deoplete-go and try it.

Also, I appreciate it :)

Now I have a private repository that was developed using this. I will publish after a while.
Thanks again for accessible API, and wonderfully fast remote interface.

Regards

**Pull request merged**
